"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.peliculas = void 0;
exports.peliculas = [
    {
        titulo: "Poli de Guardería",
        resumen: "Un policia que se hace pasar por profesor de guarderia",
        genero: "Familiar",
        masVisto: false,
        calificacionImdb: 5.6,
        premioGalardon: false,
        fechaEstreno: new Date("1990-12-21"),
        imagen: "./public/poli-guarderia.png",
    },
    {
        titulo: "The Karate Kid",
        resumen: "Un niño que aprende karate",
        genero: "Familiar",
        masVisto: true,
        calificacionImdb: 7.2,
        premioGalardon: false,
        fechaEstreno: new Date("1984-06-22"),
        imagen: "./public/karate-kid.png",
    },
    {
        titulo: "El príncipe de Zamunda",
        resumen: "Un principe africano que se va a Nueva York a buscar esposa",
        genero: "Familiar",
        masVisto: false,
        calificacionImdb: 7,
        premioGalardon: false,
        fechaEstreno: new Date("1988-06-29"),
        imagen: "./public/principe-zamunda.png",
    },
    {
        titulo: "Angry Birds",
        resumen: "Una pelicula de los pajaros de angry birds",
        genero: "Animacion",
        masVisto: false,
        calificacionImdb: 6.3,
        premioGalardon: false,
        fechaEstreno: new Date("2016-05-11"),
        imagen: "./public/angry-birds.png",
    },
    {
        titulo: "Babe el cerdito valiente",
        resumen: "Un cerdito que quiere ser perro pastor",
        genero: "Familiar",
        masVisto: true,
        calificacionImdb: 6.7,
        premioGalardon: true,
        fechaEstreno: new Date("1995-08-04"),
        imagen: "./public/babe.png",
    },
    {
        titulo: "Los Croods",
        resumen: "Una familia de cavernicolas que se encuentra con un hombre moderno",
        genero: "Animacion",
        masVisto: false,
        calificacionImdb: 7.2,
        premioGalardon: false,
        fechaEstreno: new Date("2013-03-15"),
        imagen: "./public/croods.png",
    },
    {
        titulo: "José, el rey de los sueños",
        resumen: "La historia de José de la biblia",
        genero: "Animacion",
        masVisto: false,
        calificacionImdb: 6.5,
        premioGalardon: false,
        fechaEstreno: new Date("2000-10-27"),
        imagen: "./public/jose.png",
    },
    {
        titulo: "La patrulla canina",
        resumen: "Una pelicula de la patrulla canina",
        genero: "Animacion",
        masVisto: false,
        calificacionImdb: 4.7,
        premioGalardon: false,
        fechaEstreno: new Date("2021-08-20"),
        imagen: "./public/patrulla-canina.png",
    },
    {
        titulo: "Los pitufos",
        resumen: "Una pelicula de los pitufos",
        genero: "Animacion",
        masVisto: false,
        calificacionImdb: 5.4,
        premioGalardon: false,
        fechaEstreno: new Date("2011-07-29"),
        imagen: "./public/pitufos.png",
    },
    {
        titulo: "El cazador y la reina del hielo",
        resumen: "La historia de la reina del hielo",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 6.1,
        premioGalardon: false,
        fechaEstreno: new Date("2016-04-08"),
        imagen: "./public/cazador.png",
    },
    {
        titulo: "Ghost Rider",
        resumen: "Un hombre que se convierte en un esqueleto en llamas",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 5.2,
        premioGalardon: false,
        fechaEstreno: new Date("2007-02-16"),
        imagen: "./public/ghost-rider.png",
    },
    {
        titulo: "La momia",
        resumen: "La historia de la momia",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 5.2,
        premioGalardon: false,
        fechaEstreno: new Date("2008-08-01"),
        imagen: "./public/momia.png",
    },
    {
        titulo: "Vampire Academy",
        resumen: "Una academia de vampiros",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 5.5,
        premioGalardon: false,
        fechaEstreno: new Date("2014-02-14"),
        imagen: "./public/vampire-academy.png",
    },
    {
        titulo: "Warcraft: El origen",
        resumen: "La historia de Warcraft",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 6.8,
        premioGalardon: false,
        fechaEstreno: new Date("2016-06-03"),
        imagen: "./public/warcraft.png",
    },
    {
        titulo: "Intocable",
        resumen: "Un hombre que se queda tetraplejico y contrata a un cuidador",
        genero: "Familiar",
        masVisto: true,
        calificacionImdb: 8.5,
        premioGalardon: true,
        fechaEstreno: new Date("2011-11-02"),
        imagen: "./public/intocable.png",
    },
];
